name = "subdued"
version = "0.1.0"
description = "A dom manipulation library for gleam"
licences = ["Apache-2.0"]
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
