name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "1.6.1"
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
